[package]
name = "mcpe_motd"
authors = ["Mikhail Lavelin <github.com/mikhaillav>"]
description = "A library to fetch some information from MCPE (MCBE actually) over raknet"

version = "0.1.0"
edition = "2021"

[dependencies]
